services:
  mainapp:
    build: ./mainapp
    environment:
      - PORT=3000
    ports:
      - 80:3000
    working_dir: /mainapp
    volumes:
      - ./mainapp/:/mainapp
  counter:
    build: ./server
    environment:
      - PORT=4000
      - REDIS_URL=redis://storage
    ports:
      - 4000:4000
    working_dir: /server
    volumes:
      - ./server/:/server
    depends_on:
      - storage
    links: ["mainapp"]
  storage:
    image: redis
    volumes:
      - ./data:/data